Add ClaimToGroupMapper
appuio/appuio-keycloak-extensions pull request #1
Opened 2021-09-10 16:09 UTC by ccremer

2021-09-13 08:02 UTC, corvus-ch requested changes
Please remove the reference to our LDAP group name.

The current build assumes the java built tools to be available on a system. This is probably fine for a Java development company. For us this could be an issue when having to investigate a build failure. Consider to make use of multi step container build instead.

2021-09-13 12:13 UTC, bastjan reviewed
I would prefer a docker two stage build and running the tests in a container too. Otherwise LGTM 🚀

2021-09-21 15:03 UTC, ccremer commented
Added multi-stage build

2021-09-23 08:43 UTC, bastjan approved these changes

2021-09-23 09:21 UTC, merged